version: "3.9"
services:
  client:
    image: node:14-buster-slim
    container_name: ZoomClient
    ports:
      - 9999:9999
    working_dir: /Client
    volumes:
      - /HolismReact/Zoom/Client:/Client
    command: >
      sh -c
      "
      npm install &&
      npm start &
      tail -f /dev/null
      "
  # cdn:
  #   image: node:14-buster-slim
  #   container_name: ZoomCdn
  #   ports:
  #     - 9999:9999
  #   working_dir: /CDN
  #   volumes:
  #     - /HolismReact/Zoom/CDN:/CDN
  #   command: >
  #     sh -c
  #     "
  #     npm install &&
  #     npm start &
  #     tail -f /dev/null
  #     "
